kharazmi/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('project.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

handler404 = "project.views.error404"    

project/urls.py
from django.urls import path
from . import views
app_name="urls"
urlpatterns = [
    path('' , views.startpage , name='startpage'),
    path('home/' , views.index , name='index'),
    # <Teaches>-------------------------------------------
    path('paye7/' , views.theaches7 , name='paye7'),
    path('paye8/' , views.theaches8 , name='paye8'),
    path('paye9/' , views.theaches9 , name='paye9'),
    #-----------------------------------------------------
    # <Seasons>----------------------------------------------------------------
    # <Paye7>----------------------------------------------------------
    path('paye7/season1/' , views.Paye7_season1 , name='paye7_season1'),
    path('paye7/season2/' , views.Paye7_season2 , name='paye7_season2'),
    path('paye7/season3/' , views.Paye7_season3 , name='paye7_season3'),
    path('paye7/season4/' , views.Paye7_season4 , name='paye7_season4'),
    path('paye7/season5/' , views.Paye7_season5 , name='paye7_season5'),
    path('paye7/season6/' , views.Paye7_season6 , name='paye7_season6'),
    path('paye7/season7/' , views.Paye7_season7 , name='paye7_season7'),
    path('paye7/season8/' , views.Paye7_season8 , name='paye7_season8'),
    path('paye7/season9/' , views.Paye7_season9 , name='paye7_season9'),
    # -----------------------------------------------------------------
    # <Paye8>----------------------------------------------------------
    path('paye8/season1/' , views.Paye8_season1 , name='paye8_season1'),
    path('paye8/season2/' , views.Paye8_season2 , name='paye8_season2'),
    path('paye8/season3/' , views.Paye8_season3 , name='paye8_season3'),
    path('paye8/season4/' , views.Paye8_season4 , name='paye8_season4'),
    path('paye8/season5/' , views.Paye8_season5 , name='paye8_season5'),
    path('paye8/season6/' , views.Paye8_season6 , name='paye8_season6'),
    path('paye8/season7/' , views.Paye8_season7 , name='paye8_season7'),
    path('paye8/season8/' , views.Paye8_season8 , name='paye8_season8'),
    path('paye8/season9/' , views.Paye8_season9 , name='paye8_season9'),
    # -----------------------------------------------------------------
    # <Paye9>----------------------------------------------------------
    path('paye9/season1/' , views.Paye9_season1 , name='paye9_season1'),
    path('paye9/season2/' , views.Paye9_season2 , name='paye9_season2'),
    path('paye9/season3/' , views.Paye9_season3 , name='paye9_season3'),
    path('paye9/season4/' , views.Paye9_season4 , name='paye9_season4'),
    path('paye9/season5/' , views.Paye9_season5 , name='paye9_season5'),
    path('paye9/season6/' , views.Paye9_season6 , name='paye9_season6'),
    path('paye9/season7/' , views.Paye9_season7 , name='paye9_season7'),
    path('paye9/season8/' , views.Paye9_season8 , name='paye9_season8'),
    # -----------------------------------------------------------------
    # -------------------------------------------------------------------------
    # <Lessons>----------------------------------------------------------------
    path('<slug:slug>' , views.Lesson , name='lessons'),
    # -------------------------------------------------------------------------
    # <register user>----------------------------------------------------------
    # <signup>
    path('signup/' , views.user_signup , name="signup"),
    # <signin>
    path('signin/' , views.user_signin , name="signin"),
    # <logout>
    path('logout/' , views.user_logout , name="logout"),
    # -------------------------------------------------------------------------
    # # <Contact>----------------------------------------------------------------
    # path('contact/' , views.user_Contact , name='contact'),
    # # -------------------------------------------------------------------------
    path('firstlogin/' , views.firstlogin , name='firstlogin'),
    
    path('addafter/' , views.addafter , name='addafter'),
]

project/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    email = models.EmailField(max_length=50)
    message = models.TextField(max_length=500)
    def __str__(self):
        return self.email
class Lessons(models.Model):
    STATUS_CHOICES = (
        # paye7
        ('paye7_season1' , 'paye7_season1'),
        ('paye7_season2' , 'paye7_season2'),
        ('paye7_season3' , 'paye7_season3'),
        ('paye7_season4' , 'paye7_season4'),
        ('paye7_season5' , 'paye7_season5'),
        ('paye7_season6' , 'paye7_season6'),
        ('paye7_season7' , 'paye7_season7'),
        ('paye7_season8' , 'paye7_season8'),
        ('paye7_season9' , 'paye7_season9'),
        # paye8
        ('paye8_season1' , 'paye8_season1'),
        ('paye8_season2' , 'paye8_season2'),
        ('paye8_season3' , 'paye8_season3'),
        ('paye8_season4' , 'paye8_season4'),
        ('paye8_season5' , 'paye8_season5'),
        ('paye8_season6' , 'paye8_season6'),
        ('paye8_season7' , 'paye8_season7'),
        ('paye8_season8' , 'paye8_season8'),
        ('paye8_season9' , 'paye8_season9'),
        # paye9
        ('paye9_season1' , 'paye9_season1'),
        ('paye9_season2' , 'paye9_season2'),
        ('paye9_season3' , 'paye9_season3'),
        ('paye9_season4' , 'paye9_season4'),
        ('paye9_season5' , 'paye9_season5'),
        ('paye9_season6' , 'paye9_season6'),
        ('paye9_season7' , 'paye9_season7'),
        ('paye9_season8' , 'paye9_season8'),

    )
    title = models.CharField(max_length=100)
    paye = models.CharField(max_length=50)
    lesson = models.CharField(max_length=50)
    video = models.FileField(upload_to='video/%y')
    slug = models.SlugField(max_length=50)
    status = models.CharField(max_length=50 , choices=STATUS_CHOICES)
    def __str__(self):
        return self.slug

     

project/forms.py
from django import forms

# <class>
class loginforms(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

project/views.py
from pprint import pp
from django.shortcuts import render , get_object_or_404 , redirect
from .models import *
from .forms import *
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import login , authenticate , logout 
from django.contrib.auth.models import User
from .models import *

# Create your views here.

def startpage(request):
    return render(request , "startpage.html")

def index(request):
    return render(request , "index.html")
   
# <Teaches>-------------------------------------------------------
def theaches7(request):
    return render(request , "theaches-html/theaches7.html")

def theaches8(request):
    return render(request , "theaches-html/theaches8.html")

def theaches9(request):
    return render(request , "theaches-html/theaches9.html")    
#-----------------------------------------------------------------
# <Seasons>-------------------------------------------------------
# <Paye7>------------------------------------------------
def Paye7_season1(request):
    lessons = Lessons.objects.filter(status='paye7_season1')
    return render(request , "Seasons/Paye7/season1.html" , {'lesson' : lessons})

def Paye7_season2(request):
    lessons = Lessons.objects.filter(status='paye7_season2')
    return render(request , "Seasons/Paye7/season2.html" , {'lesson' : lessons})

def Paye7_season3(request):
    lessons = Lessons.objects.filter(status='paye7_season3')
    return render(request , "Seasons/Paye7/season3.html" , {'lesson' : lessons})

def Paye7_season4(request):
    lessons = Lessons.objects.filter(status='paye7_season4')
    return render(request , "Seasons/Paye7/season4.html" , {'lesson' : lessons})

def Paye7_season5(request):
    lessons = Lessons.objects.filter(status='paye7_season5')
    return render(request , "Seasons/Paye7/season5.html" , {'lesson' : lessons})

def Paye7_season6(request):
    lessons = Lessons.objects.filter(status='paye7_season6')
    return render(request , "Seasons/Paye7/season6.html" , {'lesson' : lessons})

def Paye7_season7(request):
    lessons = Lessons.objects.filter(status='paye7_season7')
    return render(request , "Seasons/Paye7/season7.html" , {'lesson' : lessons})

def Paye7_season8(request):
    lessons = Lessons.objects.filter(status='paye7_season8')
    return render(request , "Seasons/Paye7/season8.html" , {'lesson' : lessons})

def Paye7_season9(request):
    lessons = Lessons.objects.filter(status='paye7_season9')
    return render(request , "Seasons/Paye7/season9.html" , {'lesson' : lessons})
# ------------------------------------------------------
# <Paye8>-----------------------------------------------
def Paye8_season1(request):
    lessons = Lessons.objects.filter(status='paye8_season1')
    return render(request , "Seasons/Paye8/season1.html" , {'lesson' : lessons}) 

def Paye8_season2(request):
    lessons = Lessons.objects.filter(status='paye8_season2')
    return render(request , "Seasons/Paye8/season2.html" , {'lesson' : lessons}) 

def Paye8_season3(request):
    lessons = Lessons.objects.filter(status='paye8_season3')
    return render(request , "Seasons/Paye8/season3.html" , {'lesson' : lessons}) 

def Paye8_season4(request):
    lessons = Lessons.objects.filter(status='paye8_season4')
    return render(request , "Seasons/Paye8/season4.html" , {'lesson' : lessons}) 

def Paye8_season5(request):
    lessons = Lessons.objects.filter(status='paye8_season5')
    return render(request , "Seasons/Paye8/season5.html" , {'lesson' : lessons}) 

def Paye8_season6(request):
    lessons = Lessons.objects.filter(status='paye8_season6')
    return render(request , "Seasons/Paye8/season6.html" , {'lesson' : lessons}) 

def Paye8_season7(request):
    lessons = Lessons.objects.filter(status='paye8_season7')
    return render(request , "Seasons/Paye8/season7.html" , {'lesson' : lessons}) 

def Paye8_season8(request):
    lessons = Lessons.objects.filter(status='paye8_season8')
    return render(request , "Seasons/Paye8/season8.html" , {'lesson' : lessons}) 

def Paye8_season9(request):
    lessons = Lessons.objects.filter(status='paye8_season9')
    return render(request , "Seasons/Paye8/season9.html" , {'lesson' : lessons})     
# ------------------------------------------------------
# <Paye9>-----------------------------------------------  
def Paye9_season1(request):
    lessons = Lessons.objects.filter(status='paye9_season1')
    return render(request , "Seasons/Paye9/season1.html" , {'lesson' : lessons})  

def Paye9_season2(request):
    lessons = Lessons.objects.filter(status='paye9_season2')
    return render(request , "Seasons/Paye9/season2.html" , {'lesson' : lessons}) 

def Paye9_season3(request):
    lessons = Lessons.objects.filter(status='paye9_season3')
    return render(request , "Seasons/Paye9/season3.html" , {'lesson' : lessons}) 

def Paye9_season4(request):
    lessons = Lessons.objects.filter(status='paye9_season4')
    return render(request , "Seasons/Paye9/season4.html" , {'lesson' : lessons}) 

def Paye9_season5(request):
    lessons = Lessons.objects.filter(status='paye9_season5')
    return render(request , "Seasons/Paye9/season5.html" , {'lesson' : lessons}) 

def Paye9_season6(request):
    lessons = Lessons.objects.filter(status='paye9_season6')
    return render(request , "Seasons/Paye9/season6.html" , {'lesson' : lessons}) 

def Paye9_season7(request):
    lessons = Lessons.objects.filter(status='paye9_season7')
    return render(request , "Seasons/Paye9/season7.html" , {'lesson' : lessons}) 

def Paye9_season8(request):
    lessons = Lessons.objects.filter(status='paye9_season8')
    return render(request , "Seasons/Paye9/season8.html" , {'lesson' : lessons}) 
# ------------------------------------------------------  
# ---------------------------------------------------------------- 
# <Lessons>-------------------------------------------------------
def Lesson(request , slug):
    lesson = get_object_or_404 (Lessons , slug=slug)
    return render(request , 'Lessons.html' , {'lessons':lesson})
# ---------------------------------------------------------------- 


# <register user>-------------------------------------------------
# <sign up>---------------------------------------------
def user_signup(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        pass1 = request.POST['pass']
        cpass = request.POST['cpass']

        if User.objects.filter(username=username):
            messages.error(request , '!این نام کاربری قبلا استفاده شده است')
            return redirect('urls:signup')

        if len(username)<4 or len(username)>20:
            messages.error(request , '!نام کاربری حداقل باید شامل 4 کرکتر و حداکثر 20 کرکتر باشد')
            return redirect('urls:signup')       

        if User.objects.filter(email=email):
            messages.error(request , '!این ایمیل قبلا استفاده شده است') 
            return redirect('urls:signup')   

        if pass1 != cpass:
            messages.error(request , '!رمز عبور مطابقت ندارد')
            return redirect('urls:signup')


        myuser = User.objects.create_user( username , email , pass1 )

        myuser.save()

        messages.success(request , '!حساب کاربری شما با موفقیت ساخته شد')
        return redirect('urls:signin')

    return render(request , 'register-pages/signup.html')
# ------------------------------------------------------
# <signin>----------------------------------------------
def user_signin(request):
    if request.method == 'POST':
        form = loginforms(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request , username = cd['username'] , password = cd['password'])
            if user is not None:
                if user.is_active:
                    login(request , user)
                    messages.success(request , 'شما با موفقیت وارد حساب کاربری خود شدید!')
                    return redirect("urls:index")
                else:
                    messages.error(request , '!حساب کاربری شما مسدود شده است')
            else:
                messages.error(request , "!اطلاعات وارد شده صحیح نمیباشد")
                return redirect('urls:signin')
    else:
        form = loginforms()
    return render(request , 'register-pages/signin.html')
# ------------------------------------------------------
# <logout>----------------------------------------------
def user_logout(request):
    logout(request)
    messages.success(request , 'شما با موفقیت از حساب کاربری خود خارج شدید!')
    return redirect("urls:index")
# ------------------------------------------------------
# ----------------------------------------------------------------
# # <Contact>-------------------------------------------------------
# def user_Contact(request):
#     if request.method == 'POST':
#         email = request.POST['email']
#         message = request.POST['message']
#         Contact.objects.create(email=email , message=message)
#         messages.success(request , "پیام شما به دست ما رسید! به زودی از طریق ایمیل به ان پاسخ خواهیم داد")
#         return redirect('urls:contact')

#         return render(request , 'contact.html')
#     else:
#         return render(request , 'contact.html')
# # ----------------------------------------------------------------
def firstlogin(request):
    return render(request , 'includes/firstlogin.html')   

def addafter(request):
    return render(request , 'addafter.html')  

def error404(request , exception):
    return render(request , 'error404.html')

project/templates/includes/alert.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/alert.css' %}">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
</head>
<body>
{% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="alert-error show">
        <span><i class="fa-solid fa-triangle-exclamation"></i></span>
        <span class="massage-error">{{message}}</span>
        <span class="close-btn-error">
            <span><i class="fa-solid fa-xmark"></i></span>
        </span>
    </div>
    {% else %}
    <div class="alert-success hide">
        <span><i class="fa-solid fa-circle-check"></i></span>
        <span class="massage-success">{{message}}</span>
        <span class="close-btn-success">
            <span><i class="fa-solid fa-xmark"></i></span>
        </span>
    </div>
    {% endif %}
{% endfor %}
<script src="{% static 'js/alert.js' %}"></script>
</body>

</html>

project/templates/includes/firstlogin.html
{% load static %}
{% include 'includes/Fonts-html/Yekan.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/error404.css' %}">
    <title>خطا!</title>
</head>

<body>
    <div id="div-img">
        <img src="{% static 'img/firstlogin.png' %}" alt="login image" id="img-login">
    </div>
    <h4>ورود به حساب کاربری</h4>
    <div>
        <h1>برای دسترسی به این بخش ابتدا به حساب کاربری خود وارد شوید</h1>
    </div>
    <a href="{% url 'urls:signin' %}">
        <div class="div-butten">
            <h2>ورود به حساب کاربری</h2>
        </div>
    </a>
</body>

</html>

project/templates/includes/footer.html
<footer>
    <h2 class="h2-foot">سایت سیاره ریاضی</h2>
   <i><p id="p-foot">کلیه حقوق مادی و معنوی این سایت مربوط به سایت سیاره ریاضی می باشد</p></i>
   <p id="text-foot">تحت نظر :</p>
   <b><p class="p-footer">1-اداره کل آموزش و پرورش استان خراسان رضوی</p></b>
   <b><p class="p-footer">2-هیئت داوری جشنواره خوارزمی</p></b>
   <b><p class="p-footer">3-دبیرستان شهید دانشجو</p></b>
</footer>

project/templates/includes/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'fontawesomefree/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
</head>
<header>
    <nav>
        <div class="navbar-brand">
            <img src="{% static 'img/index-img/images.jpg' %}" alt="brand">
        </div>
        <ul class="navbar-ul">
            <li class="li-item"><a href="{% url 'urls:index' %}">خانه</a></li>
            <li class="li-item"><a href="{% url 'urls:addafter' %}">بانک سوال</a>
                <ul>
                    <li><a href="{% url 'urls:addafter' %}">هفتم</a></li>
                    <li><a href="{% url 'urls:addafter' %}">هشتم</a></li>
                    <li><a href="{% url 'urls:addafter' %}">نهم</a></li>
                </ul>
            </li>
            <li class="li-item"><a href="{% url 'urls:addafter' %}">آزمون</a>
                <ul>
                    <li><a href="{% url 'urls:addafter' %}">هفتم</a></li>
                    <li><a href="{% url 'urls:addafter' %}">هشتم</a></li>
                    <li><a href="{% url 'urls:addafter' %}">نهم</a></li>
                </ul>
            </li>
            <li class="li-item"><a href="{% url 'urls:addafter' %}">ارتباط با ما</a></li>
            <div class="login-btn">
                {% if request.user.is_authenticated %}
                <a href="{% url 'urls:logout' %}" class="register">خروج</a>
                {% else %}
                <a href="{% url 'urls:signin' %}" class="login">ورود</a>
                <a href="{% url 'urls:signup' %}" class="register">ثبت نام</a>
                {% endif %}
            </div>
        </ul>

       
    </nav>
    <div class="theme"></div>
</header>